### ISSUE TITLE
uptime limit tidak jalan

### ISSUE THREAD

**Issue by zukrodin** [ibnux/phpmixbill#1]
limit uptime di mikrotik tidak nongol, sehingga tidak bisa di bikin voucer per jam 
![image](https://cloud.githubusercontent.com/assets/24580209/24083599/a1516d66-0d0c-11e7-92d3-8b93bc596c39.png)
![image](https://cloud.githubusercontent.com/assets/24580209/24083612/c9480028-0d0c-11e7-82d2-8d7d41dc6cb8.png)

**Comment by ibnux** [comment]
Phpmixbill mengandalkan cronjob untuk pengecekan batas pemakaian. 
Pastikan cronjob nya aktif. 

Jika ada paket per jam, tiap jam cronjob harus melakukan  pengecekan
Cek dibagian wiki untuk cronjob

**Comment by ibnux** [comment]
Limit uptime hanya dimunculkan jika User sudah expired, nanti bakalan diisi 5menit oleh cronjob, biar User bisa login, tapi gak lama expired

**Comment by ibnux** [comment]
#cdc9e5f9d82078c8f6cc32bd638067344bc60184

Sudah beres
