### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by andri3d** [ibnux/phpmixbill#24]
https://github.com/ibnux/phpmixbill/blob/9b329ed9f5131b069b249f11b21b380a4080e22f/system/autoload/Password.php#L14

Fatal error: Uncaught ArgumentCountError: crypt() expects exactly 2 arguments, 1 given in D:\Xampp\htdocs\phpmixbill\system\autoload\Password.php:14 Stack trace: #0 D:\Xampp\htdocs\phpmixbill\system\autoload\Password.php(14): crypt('mypassword') #1 D:\Xampp\htdocs\phpmixbill\system\controllers\settings.php(128): Password::_crypt('mypassword') #2 D:\Xampp\htdocs\phpmixbill\system\boot.php(207): include('D:\\Xampp\\htdocs...') #3 D:\Xampp\htdocs\phpmixbill\index.php(13): require('D:\\Xampp\\htdocs...') #4 {main} thrown in D:\Xampp\htdocs\phpmixbill\system\autoload\Password.php on line 14

**Comment by youssefoukh** [comment]
I heard password_hash is better to use along with password_verify.

**Comment by ibnux** [comment]
download latest release
