### ISSUE TITLE
Help connection with mikrotik

### ISSUE THREAD

**Issue by faibacon** [ibnux/phpmixbill#27]
Hi how can i connect with my mikrotik using public ip? and on clients side, i want them to pay via mobile payment and reactivated automatic using transaction code, is that possible?

**Comment by faibacon** [comment]
Error code after new update
Parse error: syntax error, unexpected 'null' (T_STRING), expecting ';' in C:\xampp\htdocs\sky2\system\autoload\PEAR2\Net\RouterOS\Client.php on line 284

**Comment by tamzid001** [comment]
im having the same issue

**Comment by ibnux** [comment]
download latest release
