### ISSUE TITLE
error connect

### ISSUE THREAD

**Issue by rabi29** [ibnux/phpmixbill#3]
hi,
after install i can t connet because a have  `error` 

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 La table 'api2.tbl_users' n'existe pas' in C:\wamp64\www\apiv5\system\orm.php on line 435

( ! ) PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 La table 'api2.tbl_users' n'existe pas in C:\wamp64\www\apiv5\system\orm.php on line 435

> 

no table api2.tbl_users

thank

**Comment by qibinghua** [comment]
You need import sql file manualy

**Comment by rabi29** [comment]
hi,
i do it but no access with loggin admin 123456

best regards

**Comment by rabi29** [comment]
it s ok 

sorry
thank for your quick reply
