### ISSUE TITLE
Kang ibnux tolong update masa aktif voucher per jam

### ISSUE THREAD

**Issue by fuchmi** [ibnux/phpmixbill#36]
assalamualikum....

kang saya mau kasi saran untuk masa aktif voucher kan cm per hari dan bulanan..

tolong dong ditambahkan untuk per jam nya....

terima kasih

**Comment by ibnux** [comment]
Sedang dibuat mulai per menit juga

**Comment by fuchmi** [comment]
akses home pages

Fatal error: Uncaught --> Smarty: Unable to load template 'file:/www/wwwroot/cmi.my.id/system/../pages/Announcement.html' in 'login.tpl' <-- thrown in /www/wwwroot/cmi.my.id/system/vendors/smarty/libs/sysplugins/smarty_internal_template.php on line 195

**Comment by ibnux** [comment]
Kalo ambil dari git
Ubah folder page_template jadi page

Dari master masih on progress juga

**Comment by fuchmi** [comment]
ok siap dah bisa home page

saya ambil dari devploment

tgl yg perjam dan permenit msh error

Fatal error: Uncaught PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'validity_unit' at row 1 in /www/wwwroot/cmi.my.id/system/orm.php:435 Stack trace: #0 /www/wwwroot/cmi.my.id/system/orm.php(435): PDOStatement->execute() #1 /www/wwwroot/cmi.my.id/system/orm.php(2010): ORM::_execute() #2 /www/wwwroot/cmi.my.id/system/controllers/services.php(261): ORM->save() #3 /www/wwwroot/cmi.my.id/system/boot.php(238): include('/www/wwwroot/cm...') #4 /www/wwwroot/cmi.my.id/index.php(6): require('/www/wwwroot/cm...') #5 {main} thrown in /www/wwwroot/cmi.my.id/system/orm.php on line 435

**Comment by ibnux** [comment]
Pasti error
Ada perubahan di database
Belum saya masukkan ke sql di installer

**Comment by diantower** [comment]
Assalamualaikum
Pak ibnux terima kasih banyak untuk program phpmixbill nya, ini lagi coba install di hosting pribadi. Apakah phpmixbill ini bisa untuk pelanggan rumahan bukan hotspot ? Karena sy lihat menu2 nya lebih ke arah client hotspotan...maturnuwun atensinya

**Comment by ibnux** [comment]
Waalaikum salam
@diantower pada dasarnya phpmixbill untuk kelas RTRW net. Jadi jualannya voucher ke yang langganan internet. Dan itu menggunakan fitur hotspot di mikrotik.
Kaya voucher pulsa

**Comment by diantower** [comment]
Kalo model nya seperti tagihan internet bulanan punya pak ?
Saya kesulitan rubah menu nya menyesuaikan kebutuhan tagihan bulanan

**Comment by fuchmi** [comment]
@ibnux siap kang...

**Comment by fuchmi** [comment]
sudah ok kang...

ini lagi saya coba2 dl yg lain dan fitur payment geteway...

btw fitur whatsapp geteway blom muncul hehehhe

gandengan dengan starsender atau wablas juga ok

**Comment by ibnux** [comment]
Ah iya
Passwordnya admin:admin 😅

Ini wa gateway memang kebanyakan. Beda beda API. Jadi saya pake yang sederhana yang saya bikin sendiri 🤣

Nanti terakhir saya masukin gateway gateway yang ada

**Comment by fuchmi** [comment]
Kang masukan lagi ne...

1. Voucher generate langsung masuk ke mikrotik. Data vouchernya. Dan di buat klo voucher belum terpakai masa aktif blom jalan.
Seperti billing tetangga, atau langsung ke radius...
Klo lbh simple langsung ke mikrotik.
Di buat 2 versi juga bisa... 

2. Untuk pppoe/bulanan ada remider/pemberitahuan ke pelanggan klo paket sebelum 2 hari jatuh tempo, dan hari jatuh tempo, di kirem via WA gateway 

3. Dan voucher nya bisa di beli melalui page login.. via payment gateway. - Klo ribet yg ini bs di skip 😁

4. Vouchernya di buat huruf kecil aja, dan huruf kecil angka, angka saja.

5. Di buatkan juga page donasi untuk developer saat install ini billing ada kode aktivasi. Dari sang developer. Jadi kode unix aktivasi nanti di kasi sama developer untuk aktivasi billing ini. klo gk keberatan 😁

**Comment by ibnux** [comment]
1. tidak memungkinkan
2. mungkin bila nanti
3. sudah dibuat, tapi bukan beli voucher, Paket yang dibeli dan langsung aktif
4. mungkin bila nanti
5. sudah ada halaman khusus, tapi ga ada aktivasi

silahkan lanjut ke bagian [diskusi](https://github.com/ibnux/phpmixbill/discussions) untuk ide dan saran

**Comment by fuchmi** [comment]
Ok siap
