### ISSUE TITLE
Adakah model billing pelanggan rumahan bukan hotspotan

### ISSUE THREAD

**Issue by diantower** [ibnux/phpmixbill#38]
Assalamualaikum
Pak ibnux terima kasih banyak untuk program phpmixbill nya, ini lagi coba install di hosting pribadi. Apakah phpmixbill ini bisa untuk pelanggan rumahan bukan hotspot ? Karena sy lihat menu2 nya lebih ke arah client hotspotan...maturnuwun atensinya

**Comment by ibnux** [comment]
Pelanggan Rumahan itu ya pake Hotspot, ini kan hanya billing, jalurnya mau pakai Wifi atau kabel, yang penting lewat Mikrotik dulu

**Comment by ibnux** [comment]
Silahkan pindah ke [Diskusi](https://github.com/ibnux/phpmixbill/discussions)
