### ISSUE TITLE
instalasi tidak berhasil

### ISSUE THREAD

**Issue by agungLintas17** [ibnux/phpmixbill#40]
setelah install muncul

 Notice: Trying to access array offset on value of type null in /home/u4590234/public_html/linnet/ui/compiled/f060e365667d27117c64a60d290886de6b8dd78f_0.file.prepaid.tpl.php on line 122

**Comment by agungLintas17** [comment]
banyak sekali notifikasi begitu

**Comment by ibnux** [comment]
itu karena PHP nya menampilkan error, warning dan notice

harus diset di php.ini

atau simpan di config.php

```php
<?php
// config.php
error_reporting(E_ERROR);
ini_set('display_errors', 0);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

$db_host
```

https://stackoverflow.com/questions/15949304/turn-off-display-errors-using-file-php-ini
