### ISSUE TITLE
Undefinned Arrey and etc.

### ISSUE THREAD

**Issue by sarifulshikder** [ibnux/phpmixbill#41]
Hello Sir i am not good in coding thats why i waste my whole day to solve this kind of issue but i failed . now i want your help please help me .......
<html>
<body>

Notice: Undefined index: _MENU_AFTER_DASHBOARD in C:\wamp64\www\phpmixbill\ui\compiled\be1bb05bcc8d35c3828211a9e36aa7351556cc25_0.file.header.tpl.php on line 192
--

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>

Notice: Trying to get property 'value' of non-object in C:\wamp64\www\phpmixbill\ui\compiled\be1bb05bcc8d35c3828211a9e36aa7351556cc25_0.file.header.tpl.php on line 192
--

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>

Notice: Undefined index: _MENU_AFTER_CUSTOMERS in C:\wamp64\www\phpmixbill\ui\compiled\be1bb05bcc8d35c3828211a9e36aa7351556cc25_0.file.header.tpl.php on line 213
--

<br class="Apple-interchange-newline">
</body>
</html>

And Many All This Thing is Showing

**Comment by ibnux** [comment]
You need to disable show error in php.ini

Because i am not checking is the data exists or not

This happen if you use it on windows with xampp or wamp, or in development mode

https://stackoverflow.com/questions/15949304/turn-off-display-errors-using-file-php-ini

**Comment by sarifulshikder** [comment]
sir then what is the other or best way to use this program ?

**Comment by ibnux** [comment]
you can add this to **config.php**, so the **Notice** will not show up again

```php
<?php
    error_reporting(E_ERROR);
    ini_set('display_errors', 0);
    ini_set('display_startup_errors', 0);
```
its better using linux, or in Raspberry Pi, mini PC linux, old laptop using linux
