### ISSUE TITLE
payment tripay error

### ISSUE THREAD

**Issue by fuchmi** [ibnux/phpmixbill#43]
`https://php.rfnet.id/img/phpmix.jpg`

settingan udah benar, pas mau klik channel pembayaran kluar seperti di gambar

**Comment by ibnux** [comment]
Aktifkan telegram bot
Setiap error akan dikirim pesannya ke telegram. Begitupun setiap transaksi yang terjadi

**Comment by fuchmi** [comment]
ini kang errornya


Tripay payment failed

{
    "success": false,
    "message": "Invalid customer email"
}

**Comment by ibnux** [comment]
Tripay wajib pake email untuk pembelinya
Jadi saya akalin pake domain webservernya, username + @domain

Kalo akses phpmixbillnya pakai IP, bakal error seperti itu, jadi harus pke domain biar bisa

Atau tunggu update dari saya dimana pembeli harus isi emailnya terlebih dahulu

**Comment by ibnux** [comment]
Ah iya 
Di mobile. Menu ngga bisa di klik

Besok diupdate, udah sih. Belum dibundel aja

**Comment by ibnux** [comment]
@fuchmi untuk fixing mobile menu

https://github.com/ibnux/phpmixbill/releases/tag/6.1.2
