### ISSUE TITLE
PHP Fatal error:  time_elapsed_string(): Unknown property 

### ISSUE THREAD

**Issue by faisalusuf** [ibnux/phpmixbill#7]
Hi,
I have deployed the PHPMIXBILL from master branch but getting errors in httpd log

[Wed Apr 11 20:36:47 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/ui/theme/default/scripts/plugins/bootstrap-colorpicker.min.js, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/localisation
[Wed Apr 11 20:36:50 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/ui/theme/default/scripts/plugins/bootstrap-colorpicker.min.js, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/users
[Wed Apr 11 20:36:50 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/ui/theme/default/scripts/plugins/bootstrap-colorpicker.min.js, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/users
[Wed Apr 11 20:36:52 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/ui/theme/default/scripts/plugins/bootstrap-colorpicker.min.js, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/app
[Wed Apr 11 20:36:52 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/ui/theme/default/scripts/plugins/bootstrap-colorpicker.min.js, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/app
[Wed Apr 11 20:36:58 2018] [error] [client 192.168.1.111] PHP Fatal error:  time_elapsed_string(): Unknown property (w) in /var/www/html/phpmixbill/system/boot.php on line 160, referer: http://192.168.1.105/phpmixbill/index.php?_route=settings/app
[Wed Apr 11 20:50:41 2018] [error] [client 192.168.1.111] File does not exist: /var/www/html/phpmixbill/scripts, referer: http://192.168.1.105/phpmixbill/index.php?_route=admin/
[Wed Apr 11 20:50:50 2018] [error] [client 192.168.1.111] PHP Fatal error:  time_elapsed_string(): Unknown property (w) in /var/www/html/phpmixbill/system/boot.php on line 174, referer: http://192.168.1.105/phpmixbill/index.php?_route=admin/
[Wed Apr 11 20:50:55 2018] [error] [client 192.168.1.111] PHP Fatal error:  time_elapsed_string(): Unknown property (w) in /var/www/html/phpmixbill/system/boot.php on line 174, referer: http://192.168.1.105/phpmixbill/index.php?_route=dashboard
[Wed Apr 11 20:51:01 2018] [error] [client 192.168.1.111] PHP Fatal error:  time_elapsed_string(): Unknown property (w) in /var/www/html/phpmixbill/system/boot.php on line 174, referer: http://192.168.1.105/phpmixbill/index.php?_route=dashboard

**Comment by ibnux** [comment]
download new release
