### ISSUE TITLE
cant login after installation

### ISSUE THREAD

**Issue by dollareffizy** [ibnux/phpmixbill#9]
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'billing.tbl_users' doesn't exist in C:\wamp64\www\billing\system\orm.php:435 Stack trace: #0 C:\wamp64\www\billing\system\orm.php(435): PDOStatement->execute() #1 C:\wamp64\www\billing\system\orm.php(1834): ORM::_execute('SELECT * FROM `...', Array, 'default') #2 C:\wamp64\www\billing\system\orm.php(613): ORM->_run() #3 C:\wamp64\www\billing\system\controllers\admin.php(21): ORM->find_one() #4 C:\wamp64\www\billing\system\boot.php(207): include('C:\\wamp64\\www\\b...') #5 C:\wamp64\www\billing\index.php(13): require('C:\\wamp64\\www\\b...') #6 {main} thrown in C:\wamp64\www\billing\system\orm.php on line 435

**Comment by amdadulhaq11** [comment]
I also have same problem. we are waiting for good response.

**Comment by danielbaricawa** [comment]
I also have the same problem. we are waiting for a good and reliable response.

Thanks for advance.

**Comment by haldirm** [comment]
What is the user and  password of the index page?

**Comment by ekiguistian59** [comment]
username admin & password

**Comment by ibnux** [comment]
download new release
